In [10]:
import pandas as pd
pd.read_parquet('/Users/sunny/Desktop/2606中银/0709自下而上大势研判/data/processed/industry_lifecycle_monthly.parquet')

,month_end,industry_old_code,industry_code,industry_name,industry_source_level,cfo,cfi,cff,stock_count,latest_report_date,latest_available_date,cfo_sign,cfi_sign,cff_sign,cashflow_pattern,lifecycle_stage,lifecycle_stage_zh
0,2007-01-31,7601010000,7601010000000000,种植业,sw_level2,1.019230e+09,-1.421012e+09,-3.668897e+08,9.0,2006-09-30,2006-10-31,+,-,-,+--,mature,成熟期
1,2007-01-31,7601010100,7601010100000000,种子,sw_level3,4.653349e+07,-3.141741e+08,-5.766291e+06,7.0,2006-09-30,2006-10-30,+,-,-,+--,mature,成熟期
2,2007-01-31,7601020000,7601020000000000,渔业,sw_level2,NaN,NaN,NaN,NaN,NaT,NaT,None,None,None,None,unknown,未知
3,2007-01-31,7601020200,7601020200000000,水产养殖,sw_level3,8.342871e+08,-2.855944e+08,-1.423166e+08,5.0,2006-09-30,2006-10-31,+,-,-,+--,mature,成熟期
4,2007-01-31,7601030000,7601030000000000,林业Ⅱ,sw_level2,2.737887e+08,-2.644537e+08,-8.790145e+07,3.0,2006-09-30,2006-12-29,+,-,-,+--,mature,成熟期
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71975,2026-08-31,760v010000,760v010000000000,个护用品,sw_level2,7.676944e+08,-4.439646e+08,-3.827708e+08,4.0,2026-03-31,2026-04-30,+,-,-,+--,mature,成熟期
71976,2026-08-31,760v010100,760v010100000000,生活用纸,sw_level3,4.778394e+09,-2.355649e+09,-2.726150e+09,8.0,2026-03-31,2026-04-28,+,-,-,+--,mature,成熟期
71977,2026-08-31,760v020100,760v020100000000,化妆品制造及其他,sw_level3,1.019553e+09,-9.516739e+08,-1.384009e+08,8.0,2026-03-31,2026-07-28,+,-,-,+--,mature,成熟期
71978,2026-08-31,760v020200,760v020200000000,品牌化妆品,sw_level3,5.287444e+09,-2.460446e+09,-2.258316e+09,8.0,2026-03-31,2026-04-30,+,-,-,+--,mature,成熟期
71979,2026-08-31,760v030000,760v030000000000,医疗美容,sw_level2,2.683746e+09,-2.573300e+09,-1.034641e+09,4.0,2026-03-31,2026-04-30,+,-,-,+--,mature,成熟期

In [12]:
df = pd.read_parquet('/Users/sunny/Desktop/2606中银/0709自下而上大势研判/data/processed/industry_lifecycle_monthly.parquet')
df['cashflow_pattern'].isna().sum()

np.int64(15671)

In [13]:
df['cfo'].isna().sum()

np.int64(15671)

In [14]:
df['industry_name'].unique()

<StringArray>
[     '种植业',       '种子',       '渔业',     '水产养殖',      '林业Ⅱ',       '饲料',
     '畜禽饲料',    '农产品加工',     '粮油加工',  '其他农产品加工',
 ...
     '大气治理',   '水务及水治理',     '固废治理',   '综合环境治理',    '环保设备Ⅲ',     '个护用品',
     '生活用纸', '化妆品制造及其他',    '品牌化妆品',     '医疗美容']
Length: 305, dtype: string

In [ ]:
pd.read_parquet('/Users/sunny/Desktop/2606中银/0709自下而上大势研判/data/processed/industry_factor_panel.parquet')

,month_end,industry_old_code,industry_code,industry_name,industry_source_level,stock_count,weight_sum,growth_g,roe_ttm,dividend_yield,growth_g_coverage,roe_ttm_coverage,dividend_yield_coverage,lifecycle_stage,lifecycle_stage_zh,cashflow_pattern
0,2007-01-31,7601010000,7601010000000000,种植业,sw_level2,8.0,1.075504e+06,-87.271779,4.166755,2.045318,1.0,1.0,0.500000,mature,成熟期,+--
1,2007-01-31,7601010100,7601010100000000,种子,sw_level3,7.0,4.309109e+05,-15.844936,-25.766806,0.974341,1.0,1.0,0.428571,mature,成熟期,+--
2,2007-01-31,7601020000,7601020000000000,渔业,sw_level2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,未知,None
3,2007-01-31,7601020200,7601020200000000,水产养殖,sw_level3,6.0,6.045681e+05,4.039692,13.873363,0.614406,1.0,1.0,0.666667,mature,成熟期,+--
4,2007-01-31,7601030000,7601030000000000,林业Ⅱ,sw_level2,3.0,2.247803e+05,4.958959,1.945625,NaN,1.0,1.0,0.000000,mature,成熟期,+--
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71975,2026-08-31,760v010000,760v010000000000,个护用品,sw_level2,4.0,1.238099e+06,-16.965855,9.868044,1.910933,1.0,1.0,1.000000,mature,成熟期,+--
71976,2026-08-31,760v010100,760v010100000000,生活用纸,sw_level3,8.0,4.447743e+06,16.758229,7.461815,2.370229,1.0,1.0,1.000000,mature,成熟期,+--
71977,2026-08-31,760v020100,760v020100000000,化妆品制造及其他,sw_level3,8.0,1.896062e+06,181.268841,2.474196,0.754913,1.0,1.0,0.250000,mature,成熟期,+--
71978,2026-08-31,760v020200,760v020200000000,品牌化妆品,sw_level3,8.0,7.919110e+06,18.420916,11.223843,2.076509,1.0,1.0,0.875000,mature,成熟期,+--
71979,2026-08-31,760v030000,760v030000000000,医疗美容,sw_level2,4.0,4.894533e+06,-56.996974,9.831638,1.269215,1.0,1.0,0.750000,mature,成熟期,+--

In [17]:
df1 = pd.read_parquet('/Users/sunny/Desktop/2606中银/0709自下而上大势研判/data/processed/industry_factor_panel.parquet')
df1[df1['lifecycle_stage'] == 'unknown']

,month_end,industry_old_code,industry_code,industry_name,industry_source_level,stock_count,weight_sum,growth_g,roe_ttm,dividend_yield,growth_g_coverage,roe_ttm_coverage,dividend_yield_coverage,lifecycle_stage,lifecycle_stage_zh,cashflow_pattern
2,2007-01-31,7601020000,7601020000000000,渔业,sw_level2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,未知,None
5,2007-01-31,7601040000,7601040000000000,饲料,sw_level2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,未知,None
6,2007-01-31,7601040100,7601040100000000,畜禽饲料,sw_level3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,未知,None
10,2007-01-31,7601060000,7601060000000000,养殖业,sw_level2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,未知,None
12,2007-01-31,7601060200,7601060200000000,肉鸡养殖,sw_level3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,未知,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71795,2026-08-31,7609030000,7609030000000000,饰品,sw_level2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,未知,None
71857,2026-08-31,760f050000,760f050000000000,旅游零售Ⅱ,sw_level2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,未知,None
71858,2026-08-31,760g010000,760g010000000000,体育Ⅱ,sw_level2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,未知,None
71895,2026-08-31,760m020000,760m020000000000,其他电源设备Ⅱ,sw_level2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,未知,None
71905,2026-08-31,760m050000,760m050000000000,电池,sw_level2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,unknown,未知,None